/// Translation maps mirroring the web `translationService.js`.
///
/// Keys are grouped by area (nav, common, auth, dashboard, ...). New keys can
/// be added as screens are built; missing keys fall back to the key itself so
/// the UI never crashes on a lookup.
class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> values = {
    'en': _en,
    'ar': _ar,
  };

  static const Map<String, String> _en = {
    // App / nav
    'app_name': 'GeoNutria',
    'nav_dashboard': 'Dashboard',
    'nav_leaf_doctor': 'Leaf Doctor',
    'nav_crop_advisor': 'Crop Advisor',
    'nav_yield': 'Yield Predictor',
    'nav_satellite': 'Satellite',
    'nav_consultant': 'Smart Assistant',
    'nav_advanced_ai': 'Advanced AI',
    'nav_profile': 'Profile',
    'nav_billing': 'Billing',
    'nav_report': 'Report',
    'nav_support': 'Support',
    'nav_more': 'More',

    // Common
    'loading': 'Loading…',
    'retry': 'Retry',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'close': 'Close',
    'confirm': 'Confirm',
    'submit': 'Submit',
    'search': 'Search',
    'refresh': 'Refresh',
    'no_data': 'No data available',
    'error_generic': 'Something went wrong',
    'required_field': 'This field is required',
    'credits': 'Credits',
    'team_credits': 'Team Credits',
    'language': 'Language',
    'theme': 'Theme',
    'logout': 'Log out',

    // Auth
    'login': 'Log in',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'username': 'Username',
    'login_with_google': 'Continue with Google',
    'forgot_password': 'Forgot password?',
    'create_account': 'Create account',
    'have_account': 'Already have an account?',
    'no_account': "Don't have an account?",
    'otp_title': 'Verify your email',
    'otp_subtitle': 'Enter the 6-digit code sent to your email',
    'otp_code': 'Verification code',
    'verify': 'Verify',
    'first_name': 'First name',
    'last_name': 'Last name',
    'phone_number': 'Phone number',
    'address': 'Address',
    'login_failed': 'Login failed. Check your credentials.',

    // Paywall / credits
    'paywall_title': 'Out of AI credits',
    'paywall_body':
        'You need more credits to use this feature. Top up to continue.',
    'top_up': 'Top up',
    'insufficient_credits': 'Insufficient AI credits',

    // Dashboard / IoT
    'select_device': 'Select device',
    'live_status': 'Live status',
    'manual_entry': 'Manual entry',
    'soil_moisture': 'Soil Moisture',
    'soil_temp': 'Soil Temperature',
    'soil_ph': 'Soil pH',
    'humidity': 'Humidity',
    'ambient_temp': 'Ambient Temperature',
    'nitrogen': 'Nitrogen (N)',
    'phosphorus': 'Phosphorus (P)',
    'potassium': 'Potassium (K)',
    'ec': 'EC',
    'salinity': 'Salinity',
    'tds': 'TDS',
    'health_status': 'Health Status',
    'history': 'History',
    'run_diagnosis': 'Run diagnosis',
    'no_devices': 'No devices assigned to your account yet.',

    // Tabs & feature labels
    'tab_live': 'Live',
    'tab_history': 'History',
    'tab_weather': 'Weather',
    'tab_manual': 'Manual',
    'tab_indices': 'Indices',
    'tab_palm_count': 'Palm count',
    'tab_profile': 'Profile',
    'tab_assets': 'Assets',
    'tab_team': 'Team',
    'leaf_general': 'General',
    'leaf_palm': 'Palm',
  };

  static const Map<String, String> _ar = {
    'app_name': 'جيونوتريا',
    'nav_dashboard': 'لوحة التحكم',
    'nav_leaf_doctor': 'طبيب الأوراق',
    'nav_crop_advisor': 'مستشار المحاصيل',
    'nav_yield': 'توقع المحصول',
    'nav_satellite': 'الأقمار الصناعية',
    'nav_consultant': 'المساعد الذكي',
    'nav_advanced_ai': 'الذكاء المتقدم',
    'nav_profile': 'الملف الشخصي',
    'nav_billing': 'الفواتير',
    'nav_report': 'التقرير',
    'nav_support': 'الدعم',
    'nav_more': 'المزيد',

    'loading': 'جارٍ التحميل…',
    'retry': 'إعادة المحاولة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'submit': 'إرسال',
    'search': 'بحث',
    'refresh': 'تحديث',
    'no_data': 'لا توجد بيانات',
    'error_generic': 'حدث خطأ ما',
    'required_field': 'هذا الحقل مطلوب',
    'credits': 'الرصيد',
    'team_credits': 'رصيد الفريق',
    'language': 'اللغة',
    'theme': 'المظهر',
    'logout': 'تسجيل الخروج',

    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'username': 'اسم المستخدم',
    'login_with_google': 'المتابعة عبر جوجل',
    'forgot_password': 'نسيت كلمة المرور؟',
    'create_account': 'إنشاء حساب',
    'have_account': 'لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'otp_title': 'تأكيد بريدك الإلكتروني',
    'otp_subtitle': 'أدخل الرمز المكوّن من 6 أرقام المرسل إلى بريدك',
    'otp_code': 'رمز التحقق',
    'verify': 'تحقق',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'phone_number': 'رقم الهاتف',
    'address': 'العنوان',
    'login_failed': 'فشل تسجيل الدخول. تحقق من بياناتك.',

    'paywall_title': 'نفد رصيد الذكاء الاصطناعي',
    'paywall_body': 'تحتاج إلى مزيد من الرصيد لاستخدام هذه الميزة. أعد الشحن للمتابعة.',
    'top_up': 'إعادة الشحن',
    'insufficient_credits': 'رصيد الذكاء الاصطناعي غير كافٍ',

    'select_device': 'اختر الجهاز',
    'live_status': 'الحالة المباشرة',
    'manual_entry': 'إدخال يدوي',
    'soil_moisture': 'رطوبة التربة',
    'soil_temp': 'حرارة التربة',
    'soil_ph': 'حموضة التربة',
    'humidity': 'الرطوبة',
    'ambient_temp': 'الحرارة المحيطة',
    'nitrogen': 'النيتروجين (N)',
    'phosphorus': 'الفوسفور (P)',
    'potassium': 'البوتاسيوم (K)',
    'ec': 'التوصيل الكهربائي',
    'salinity': 'الملوحة',
    'tds': 'إجمالي المواد الذائبة',
    'health_status': 'الحالة الصحية',
    'history': 'السجل',
    'run_diagnosis': 'تشغيل التشخيص',
    'no_devices': 'لا توجد أجهزة مرتبطة بحسابك بعد.',

    'tab_live': 'مباشر',
    'tab_history': 'السجل',
    'tab_weather': 'الطقس',
    'tab_manual': 'يدوي',
    'tab_indices': 'المؤشرات',
    'tab_palm_count': 'عدّ النخيل',
    'tab_profile': 'الملف',
    'tab_assets': 'الأصول',
    'tab_team': 'الفريق',
    'leaf_general': 'عام',
    'leaf_palm': 'نخيل',
  };
}
