/// Translation maps mirroring the web `translationService.js`.
///
/// Keys are grouped by area (nav, common, auth, dashboard, ...). New keys can
/// be added as screens are built; missing keys fall back to the key itself so
/// the UI never crashes on a lookup.
class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> values = {'en': _en, 'ar': _ar};

  static const Map<String, String> _en = {
    'sat_no_data': 'No valid data',
    'sat_ndvi_low': 'Barren rock/sand',
    'sat_ndvi_mod': 'Sparse vegetation',
    'sat_ndvi_high': 'Moderate vegetation (Healthy)',
    'sat_ndvi_vhigh': 'Dense vegetation (Very Healthy)',
    'sat_ndmi_low': 'Water stress detected (Dry)',
    'sat_ndmi_mod': 'Moderate water content',
    'sat_ndmi_high': 'High water content (No Stress)',
    'sat_ndwi_flood': 'Water body detected',
    'sat_ndwi_wet': 'High soil moisture',
    'sat_ndwi_dry': 'Dry soil / Drought conditions',
    'sat_ndre_low': 'Low Nitrogen/Stressed',
    'sat_ndre_high': 'Optimal Nitrogen levels',
    'sat_gndvi_low': 'Low vigor',
    'sat_gndvi_mod': 'Moderate vigor',
    'sat_gndvi_high': 'High vigor',
    'sat_savi_arid': 'Desert/Arid soil',
    'sat_savi_growth': 'Germination/Early growth',
    'sat_savi_canopy': 'Full Canopy',
    'sat_analysis_ok': 'Analysis complete',
    // App / nav
    'app_name': 'GeoNutria',
    'nav_dashboard': 'Dashboard',
    'nav_control': 'Control & Automation',
    'nav_leaf_doctor': 'Leaf Doctor',
    'nav_crop_advisor': 'Crop Advisor',
    'nav_yield': 'Yield Predictor',
    'nav_satellite': 'Satellite',
    'nav_consultant': 'Smart Assistant',
    'nav_advanced_ai': 'Advanced AI',
    'nav_my_devices': 'My Devices',
    'nav_admin': 'Admin Dashboard',
    'quick_controls': 'Quick controls',
    'firmware_admin_only': 'Firmware updates are managed by administrators.',
    'automations': 'Automations',
    'add_rule': 'Add rule',
    'edit_rule': 'Edit rule',
    'automations_empty':
        'No rules yet. Automate a control by time of day or a sensor level.',
    'automations_unavailable':
        'Automations are unavailable right now. Your devices and controls are '
        'unaffected.',
    'when': 'When',
    'then': 'Then',
    'at_a_time': 'At a time',
    'sensor_level': 'Sensor level',
    'automation_server_time_note': 'Times follow the server clock.',
    'nav_profile': 'Profile',
    'nav_billing': 'Billing',
    'nav_report': 'Report',
    'nav_support': 'Support',
    'nav_more': 'More',

    // Common
    'loading': 'Loading…',
    'retry': 'Retry',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'close': 'Close',
    'confirm': 'Confirm',
    'submit': 'Submit',
    'search': 'Search',
    'refresh': 'Refresh',
    'no_data': 'No data available',
    'error_generic': 'Something went wrong',
    'required_field': 'This field is required',
    'credits': 'Credits',
    'team_credits': 'Team Credits',
    'language': 'Language',
    'theme': 'Theme',
    'logout': 'Log out',

    // Auth
    'login': 'Log in',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'username': 'Username',
    'login_with_google': 'Continue with Google',
    'forgot_password': 'Forgot password?',
    'create_account': 'Create account',
    'have_account': 'Already have an account?',
    'no_account': "Don't have an account?",
    'otp_title': 'Verify your email',
    'otp_subtitle': 'Enter the 6-digit code sent to your email',
    'otp_code': 'Verification code',
    'verify': 'Verify',
    'first_name': 'First name',
    'last_name': 'Last name',
    'phone_number': 'Phone number',
    'address': 'Address',
    'login_failed': 'Login failed. Check your credentials.',

    // Paywall / credits
    'paywall_title': 'Out of AI credits',
    'paywall_body':
        'You need more credits to use this feature. Top up to continue.',
    'top_up': 'Top up',
    'insufficient_credits': 'Insufficient AI credits',

    // Dashboard / IoT
    'select_device': 'Select device',
    'live_status': 'Live status',
    'manual_entry': 'Manual entry',
    'soil_moisture': 'Soil Moisture',
    'soil_temp': 'Soil Temperature',
    'soil_ph': 'Soil pH',
    'humidity': 'Humidity',
    'ambient_temp': 'Ambient Temperature',
    'nitrogen': 'Nitrogen (N)',
    'phosphorus': 'Phosphorus (P)',
    'potassium': 'Potassium (K)',
    'ec': 'EC',
    'salinity': 'Salinity',
    'tds': 'TDS',
    'health_status': 'Health Status',
    'history': 'History',
    'run_diagnosis': 'Run diagnosis',
    'no_devices': 'No devices assigned to your account yet.',

    // Tabs & feature labels
    'tab_live': 'Live',
    'tab_history': 'History',
    'tab_weather': 'Weather',
    'tab_manual': 'Manual',
    'tab_indices': 'Indices',
    'tab_palm_count': 'Palm count',
    'tab_profile': 'Profile',
    'tab_assets': 'Assets',
    'tab_team': 'Team',
    'leaf_general': 'General',
    'leaf_palm': 'Palm',

    // Deep analysis (RAG diagnosis)
    'deep_analysis': 'Deep Analysis',
    'deep_analysis_desc':
        'A full agronomic report from your live readings, the weather and '
        'your farm details.',
    'deep_analysis_no_data':
        'Needs live readings from this device. Refresh, or use Manual entry.',
    'run_deep_analysis': 'Run deep analysis',
    'view_report': 'View report',
    'run_again': 'Run again',
    'analysis_running': 'Analysing…',
    'analysis_thinking': 'Thinking…',
    'reasoning': 'Reasoning',
    'copy': 'Copy',
    'copied': 'Copied',
    'clear': 'Clear',

    // Farm context
    'farm_context': 'Farm context',
    'farm_context_hint':
        'Anything you leave blank is assumed — the report says which defaults '
        'it used.',
    'farm_context_empty': 'Add your crop and soil for a tailored analysis',
    'ctx_crop_type': 'Crop type',
    'ctx_crop_variety': 'Crop variety',
    'ctx_location': 'Location',
    'ctx_season': 'Season',
    'ctx_soil_type': 'Soil type',
    'ctx_irrigation_type': 'Irrigation type',
    'ctx_water_quantity': 'Water quantity',
    'ctx_water_unit': 'm³/Feddan/Week',
    'ctx_analysis_depth': 'Report depth',
    'nav_accounting': 'Accounting',
    'fiscal_year': 'Fiscal year',
    'revenues': 'Revenues',
    'expenses': 'Expenses',
    'net_profit': 'Net profit',
    'profit': 'Profitable',
    'loss': 'Losing money',
    'breakeven': 'Break-even',
    'add_line': 'Add line',
    'add_sub_line': 'Add sub-line',
    'no_lines_yet': 'Nothing recorded yet.',
    'unnamed': 'Untitled',
    'line_name': 'Name',
    'category_placeholder': 'Search or type a new one…',
    'add_new_category': 'Add "{name}" as a new category',
    'amount': 'Amount',
    'amount_from_children': 'Summed from the lines beneath this one',
    'optional_breakdown': 'Optional breakdown',
    'unit_price': 'Unit price',
    'quantity': 'Quantity',
    'frequency': 'Frequency',
    'frequency_hint': 'For context only — enter the amount for the whole year.',
    'freq_daily': 'Daily',
    'freq_weekly': 'Weekly',
    'freq_monthly': 'Monthly',
    'freq_seasonally': 'Seasonally',
    'freq_yearly': 'Yearly',
    'delete_line': 'Delete line',
    'delete_line_confirm': 'This line will be removed from the ledger.',
    'delete_line_children_warning':
        'This line and every line beneath it will be removed.',
    'currency_egp': 'EGP',
    'ai_advisor': 'AI advisor',
    'ai_financial_advisor': 'AI financial advisor',
    'advisor_intro':
        'Get a frank read on this year: where the money goes, what is eating '
        'the margin, and what to change.',
    'analyze_finances': 'Analyse my finances',
    'advisor_len_short': 'Brief',
    'advisor_len_medium': 'Standard',
    'advisor_len_full': 'Full report',
    'save_report': 'Save report',
    'saved': 'Saved',
    'report_history': 'Saved reports',

    // Farm Context
    'fc_title': 'Farm Context',
    'fc_collapse': 'Hide Context',
    'fc_expand': 'Show Context',
    'fc_select_farm': 'Select Farm',
    'fc_crop_type': 'Crop Type',
    'fc_crop_variety': 'Crop Variety',
    'fc_location': 'Geographic Location',
    'fc_season': 'Current Season',
    'fc_irrigation_type': 'Irrigation Type',
    'fc_water_quantity': 'Water Quantity',
    'fc_water_unit': 'm³/Feddan/Week',
    'fc_soil_type': 'Soil Type',
    'fc_analysis_depth': 'Analysis Response Depth',
    'fc_select_placeholder': 'Select...',
    'fc_custom_crop': 'Custom / Other crop...',
    'fc_enter_custom_crop': 'Enter custom crop name',
    'fc_custom_crop_hint': 'e.g. Olive, Apple, Strawberry...',
    'fc_choose_from_list': 'Choose from list',

    // Crops
    'ctx_wheat': 'Wheat',
    'ctx_rice': 'Rice',
    'ctx_maize': 'Maize',
    'ctx_cotton': 'Cotton',
    'ctx_sugarcane': 'Sugarcane',
    'ctx_berseem': 'Clover (Berseem)',
    'ctx_citrus': 'Citrus',
    'ctx_tomatoes': 'Tomatoes',
    'ctx_potatoes': 'Potatoes',
    'ctx_sugarBeet': 'Sugar Beet',
    'ctx_strawberries': 'Strawberries',
    'ctx_pomegranates': 'Pomegranates',
    'ctx_dates': 'Dates / Palm',
    'ctx_onions': 'Onions',
    'ctx_beans': 'Beans / Fava',
    'ctx_grapes': 'Grapes',
    'ctx_mangoes': 'Mangoes',

    // Locations
    'ctx_Upper Egypt': 'Upper Egypt',
    'ctx_Lower Egypt (Delta)': 'Lower Egypt (Delta)',
    'ctx_Canal Zone': 'Canal Zone',
    'ctx_Sinai': 'Sinai',
    'ctx_New Valley & Oases': 'New Valley & Oases',
    'ctx_Cairo': 'Cairo',
    'ctx_Giza': 'Giza',
    'ctx_Alexandria': 'Alexandria',
    'ctx_Faiyum': 'Faiyum',
    'ctx_Beheira': 'Beheira',
    'ctx_Sharqia': 'Sharqia',
    'ctx_Dakahlia': 'Dakahlia',
    'ctx_Gharbia': 'Gharbia',
    'ctx_Menofia': 'Menofia',
    'ctx_Qalyubia': 'Qalyubia',
    'ctx_Ismailia': 'Ismailia',
    'ctx_Suez': 'Suez',
    'ctx_Port Said': 'Port Said',
    'ctx_Matrouh': 'Matrouh',
    'ctx_Red Sea': 'Red Sea',
    'ctx_Asyut': 'Asyut',
    'ctx_Sohag': 'Sohag',
    'ctx_Qena': 'Qena',
    'ctx_Luxor': 'Luxor',
    'ctx_Aswan': 'Aswan',
    'ctx_Minya': 'Minya',
    'ctx_Beni Suef': 'Beni Suef',

    // Seasons
    'ctx_winter': 'Winter',
    'ctx_spring': 'Spring',
    'ctx_summer': 'Summer',
    'ctx_autumn': 'Autumn',

    // Irrigation Types
    'ctx_drip': 'Drip Irrigation',
    'ctx_sprinkler': 'Sprinkler Irrigation',
    'ctx_flood': 'Surface / Flood Irrigation',
    'ctx_pivot': 'Center Pivot',

    // Soil Types
    'ctx_clay': 'Clay Soil',
    'ctx_sandy': 'Sandy Soil',
    'ctx_calcareous': 'Calcareous Soil',
    'ctx_saline': 'Saline Soil',
    'ctx_silty': 'Silty Soil',

    // Analysis Depth
    'ctx_executive': 'Quick Executive Summary',
    'ctx_standard': 'Standard Technical Plan',
    'ctx_comprehensive': 'Comprehensive In-Depth Audit',
  };

  static const Map<String, String> _ar = {
    'sat_no_data': 'لا توجد بيانات',
    'sat_ndvi_low': 'صخور جرداء / رمال',
    'sat_ndvi_mod': 'نباتات متناثرة',
    'sat_ndvi_high': 'نباتات متوسطة (صحي)',
    'sat_ndvi_vhigh': 'غطاء نباتي كثيف (صحي جداً)',
    'sat_ndmi_low': 'إجهاد مائي (جاف)',
    'sat_ndmi_mod': 'محتوى مائي متوسط',
    'sat_ndmi_high': 'محتوى مائي عالي (لا يوجد إجهاد)',
    'sat_ndwi_flood': 'رصد مسطحات مائية',
    'sat_ndwi_wet': 'رطوبة تربة عالية',
    'sat_ndwi_dry': 'تربة جافة / جفاف',
    'sat_ndre_low': 'نيتروجين منخفض / إجهاد',
    'sat_ndre_high': 'مستويات نيتروجين مثالية',
    'sat_gndvi_low': 'حيوية منخفضة',
    'sat_gndvi_mod': 'حيوية متوسطة',
    'sat_gndvi_high': 'حيوية عالية',
    'sat_savi_arid': 'تربة صحراوية / قاحلة',
    'sat_savi_growth': 'إنبات / نمو مبكر',
    'sat_savi_canopy': 'غطاء كامل',
    'sat_analysis_ok': 'تم التحليل',
    'app_name': 'جيونوتريا',
    'nav_dashboard': 'لوحة التحكم',
    'nav_control': 'التحكم والأتمتة',
    'nav_leaf_doctor': 'طبيب الأوراق',
    'nav_crop_advisor': 'مستشار المحاصيل',
    'nav_yield': 'توقع المحصول',
    'nav_satellite': 'الأقمار الصناعية',
    'nav_consultant': 'المساعد الذكي',
    'nav_advanced_ai': 'الذكاء المتقدم',
    'nav_my_devices': 'أجهزتي',
    'nav_admin': 'لوحة الإدارة',
    'quick_controls': 'تحكم سريع',
    'firmware_admin_only': 'تحديثات البرنامج الثابت يديرها المسؤولون.',
    'automations': 'الأتمتة',
    'add_rule': 'إضافة قاعدة',
    'edit_rule': 'تعديل القاعدة',
    'automations_empty':
        'لا توجد قواعد بعد. يمكنك التحكم تلقائيًا حسب الوقت أو مستوى المستشعر.',
    'automations_unavailable':
        'خدمة الأتمتة غير متاحة حاليًا. أجهزتك ووسائل التحكم لم تتأثر.',
    'when': 'متى',
    'then': 'الإجراء',
    'at_a_time': 'في وقت محدد',
    'sensor_level': 'مستوى المستشعر',
    'automation_server_time_note': 'المواعيد حسب ساعة الخادم.',
    'nav_profile': 'الملف الشخصي',
    'nav_billing': 'الفواتير',
    'nav_report': 'التقرير',
    'nav_support': 'الدعم',
    'nav_more': 'المزيد',

    'loading': 'جارٍ التحميل…',
    'retry': 'إعادة المحاولة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'submit': 'إرسال',
    'search': 'بحث',
    'refresh': 'تحديث',
    'no_data': 'لا توجد بيانات',
    'error_generic': 'حدث خطأ ما',
    'required_field': 'هذا الحقل مطلوب',
    'credits': 'الرصيد',
    'team_credits': 'رصيد الفريق',
    'language': 'اللغة',
    'theme': 'المظهر',
    'logout': 'تسجيل الخروج',

    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'username': 'اسم المستخدم',
    'login_with_google': 'المتابعة عبر جوجل',
    'forgot_password': 'نسيت كلمة المرور؟',
    'create_account': 'إنشاء حساب',
    'have_account': 'لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'otp_title': 'تأكيد بريدك الإلكتروني',
    'otp_subtitle': 'أدخل الرمز المكوّن من 6 أرقام المرسل إلى بريدك',
    'otp_code': 'رمز التحقق',
    'verify': 'تحقق',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'phone_number': 'رقم الهاتف',
    'address': 'العنوان',
    'login_failed': 'فشل تسجيل الدخول. تحقق من بياناتك.',

    'paywall_title': 'نفد رصيد الذكاء الاصطناعي',
    'paywall_body':
        'تحتاج إلى مزيد من الرصيد لاستخدام هذه الميزة. أعد الشحن للمتابعة.',
    'top_up': 'إعادة الشحن',
    'insufficient_credits': 'رصيد الذكاء الاصطناعي غير كافٍ',

    'select_device': 'اختر الجهاز',
    'live_status': 'الحالة المباشرة',
    'manual_entry': 'إدخال يدوي',
    'soil_moisture': 'رطوبة التربة',
    'soil_temp': 'حرارة التربة',
    'soil_ph': 'حموضة التربة',
    'humidity': 'الرطوبة',
    'ambient_temp': 'الحرارة المحيطة',
    'nitrogen': 'النيتروجين (N)',
    'phosphorus': 'الفوسفور (P)',
    'potassium': 'البوتاسيوم (K)',
    'ec': 'التوصيل الكهربائي',
    'salinity': 'الملوحة',
    'tds': 'إجمالي المواد الذائبة',
    'health_status': 'الحالة الصحية',
    'history': 'السجل',
    'run_diagnosis': 'تشغيل التشخيص',
    'no_devices': 'لا توجد أجهزة مرتبطة بحسابك بعد.',

    'tab_live': 'مباشر',
    'tab_history': 'السجل',
    'tab_weather': 'الطقس',
    'tab_manual': 'يدوي',
    'tab_indices': 'المؤشرات',
    'tab_palm_count': 'عدّ النخيل',
    'tab_profile': 'الملف',
    'tab_assets': 'الأصول',
    'tab_team': 'الفريق',
    'leaf_general': 'عام',
    'leaf_palm': 'نخيل',

    'deep_analysis': 'التحليل العميق',
    'deep_analysis_desc':
        'تقرير زراعي متكامل من قراءات جهازك والطقس وبيانات مزرعتك.',
    'deep_analysis_no_data':
        'يحتاج قراءات مباشرة من هذا الجهاز. حدّث البيانات أو استخدم الإدخال '
        'اليدوي.',
    'run_deep_analysis': 'تشغيل التحليل العميق',
    'view_report': 'عرض التقرير',
    'run_again': 'إعادة التشغيل',
    'analysis_running': 'جارٍ التحليل…',
    'analysis_thinking': 'جارٍ التفكير…',
    'reasoning': 'خطوات التفكير',
    'copy': 'نسخ',
    'copied': 'تم النسخ',
    'clear': 'مسح',

    'farm_context': 'سياق المزرعة',
    'farm_context_hint':
        'أي حقل تتركه فارغًا سيُفترض تلقائيًا — والتقرير يوضح الافتراضات '
        'المستخدمة.',
    'farm_context_empty': 'أضف المحصول ونوع التربة للحصول على تحليل مخصص',
    'ctx_crop_type': 'نوع المحصول',
    'ctx_crop_variety': 'صنف المحصول',
    'ctx_location': 'الموقع الجغرافي',
    'ctx_season': 'الموسم',
    'ctx_soil_type': 'نوع التربة',
    'ctx_irrigation_type': 'نوع الري',
    'ctx_water_quantity': 'كمية المياه',
    'ctx_water_unit': 'م³/فدان/أسبوع',
    'ctx_analysis_depth': 'عمق التقرير',
    'nav_accounting': 'الحسابات',
    'fiscal_year': 'السنة المالية',
    'revenues': 'الإيرادات',
    'expenses': 'المصروفات',
    'net_profit': 'صافي الربح',
    'profit': 'رابحة',
    'loss': 'خاسرة',
    'breakeven': 'تعادل',
    'add_line': 'إضافة بند',
    'add_sub_line': 'إضافة بند فرعي',
    'no_lines_yet': 'لا توجد بنود بعد.',
    'unnamed': 'بدون اسم',
    'line_name': 'الاسم',
    'category_placeholder': 'ابحث أو اكتب بندًا جديدًا…',
    'add_new_category': 'إضافة "{name}" كبند جديد',
    'amount': 'المبلغ',
    'amount_from_children': 'محسوب من البنود الفرعية',
    'optional_breakdown': 'تفاصيل اختيارية',
    'unit_price': 'سعر الوحدة',
    'quantity': 'الكمية',
    'frequency': 'التكرار',
    'frequency_hint': 'للتوضيح فقط — أدخل المبلغ الخاص بالسنة كاملة.',
    'freq_daily': 'يومي',
    'freq_weekly': 'أسبوعي',
    'freq_monthly': 'شهري',
    'freq_seasonally': 'موسمي',
    'freq_yearly': 'سنوي',
    'delete_line': 'حذف البند',
    'delete_line_confirm': 'سيتم حذف هذا البند من الحسابات.',
    'delete_line_children_warning': 'سيتم حذف هذا البند وكل البنود التابعة له.',
    'currency_egp': 'ج.م',
    'ai_advisor': 'المستشار المالي',
    'ai_financial_advisor': 'المستشار المالي الذكي',
    'advisor_intro':
        'رأي صريح في سنتك: فين بتروح الفلوس، وإيه اللي بياكل المكسب، وإيه '
        'اللي محتاج يتغير.',
    'analyze_finances': 'حلّل حساباتي',
    'advisor_len_short': 'موجز',
    'advisor_len_medium': 'قياسي',
    'advisor_len_full': 'تقرير كامل',
    'save_report': 'حفظ التقرير',
    'saved': 'تم الحفظ',
    'report_history': 'التقارير المحفوظة',

    // Farm Context
    'fc_title': 'سياق المزرعة',
    'fc_collapse': 'إخفاء السياق',
    'fc_expand': 'إظهار سياق المزرعة',
    'fc_select_farm': 'اختر المزرعة',
    'fc_crop_type': 'نوع المحصول',
    'fc_crop_variety': 'صنف المحصول',
    'fc_location': 'الموقع الجغرافي',
    'fc_season': 'الموسم الحالي',
    'fc_irrigation_type': 'نوع الري',
    'fc_water_quantity': 'كمية المياه',
    'fc_water_unit': 'م³/فدان/أسبوع',
    'fc_soil_type': 'نوع التربة',
    'fc_analysis_depth': 'عمق استجابة التحليل',
    'fc_select_placeholder': 'اختر...',
    'fc_custom_crop': 'محصول آخر / يدوي...',
    'fc_enter_custom_crop': 'أدخل اسم المحصول',
    'fc_custom_crop_hint': 'مثال: زيتون، تفاح، فراولة...',
    'fc_choose_from_list': 'اختر من القائمة',

    // Crops
    'ctx_wheat': 'قمح',
    'ctx_rice': 'أرز',
    'ctx_maize': 'ذرة',
    'ctx_cotton': 'قطن',
    'ctx_sugarcane': 'قصب السكر',
    'ctx_berseem': 'برسيم',
    'ctx_citrus': 'موالح',
    'ctx_tomatoes': 'طماطم',
    'ctx_potatoes': 'بطاطس',
    'ctx_sugarBeet': 'بنجر السكر',
    'ctx_strawberries': 'فراولة',
    'ctx_pomegranates': 'رمان',
    'ctx_dates': 'بلح ونخيل',
    'ctx_onions': 'بصل',
    'ctx_beans': 'فاصوليا وفول',
    'ctx_grapes': 'عنب',
    'ctx_mangoes': 'مانجو',

    // Locations
    'ctx_Upper Egypt': 'الصعيد',
    'ctx_Lower Egypt (Delta)': 'الدلتا - وجه بحري',
    'ctx_Canal Zone': 'القناة',
    'ctx_Sinai': 'سيناء',
    'ctx_New Valley & Oases': 'الوادي الجديد والواحات',
    'ctx_Cairo': 'القاهرة',
    'ctx_Giza': 'الجيزة',
    'ctx_Alexandria': 'الإسكندرية',
    'ctx_Faiyum': 'الفيوم',
    'ctx_Beheira': 'البحيرة',
    'ctx_Sharqia': 'الشرقية',
    'ctx_Dakahlia': 'الدقهلية',
    'ctx_Gharbia': 'الغربية',
    'ctx_Menofia': 'المنوفية',
    'ctx_Qalyubia': 'القليوبية',
    'ctx_Ismailia': 'الإسماعيلية',
    'ctx_Suez': 'السويس',
    'ctx_Port Said': 'بورسعيد',
    'ctx_Matrouh': 'مطروح',
    'ctx_Red Sea': 'البحر الأحمر',
    'ctx_Asyut': 'أسيوط',
    'ctx_Sohag': 'سوهاج',
    'ctx_Qena': 'قنا',
    'ctx_Luxor': 'الأقصر',
    'ctx_Aswan': 'أسوان',
    'ctx_Minya': 'المنيا',
    'ctx_Beni Suef': 'بني سويف',

    // Seasons
    'ctx_winter': 'الشتاء',
    'ctx_spring': 'الربيع',
    'ctx_summer': 'الصيف',
    'ctx_autumn': 'الخريف',

    // Irrigation Types
    'ctx_drip': 'الري بالتنقيط',
    'ctx_sprinkler': 'الري بالرش',
    'ctx_flood': 'الري بالغمر',
    'ctx_pivot': 'الري المحوري',

    // Soil Types
    'ctx_clay': 'تربة طينية',
    'ctx_sandy': 'تربة رملية',
    'ctx_calcareous': 'تربة جيرية',
    'ctx_saline': 'تربة ملحية',
    'ctx_silty': 'تربة طميية',

    // Analysis Depth
    'ctx_executive': 'موجز تنفيذي سريع',
    'ctx_standard': 'خطة فنية قياسية',
    'ctx_comprehensive': 'تقرير تحليلي شامل وتفصيلي',
  };
}
