/// Display-only translations. API enum values and user-entered text stay intact.
const arabicUiLabels = <String, String>{
  'Country code': 'رمز الدولة',
  'Update Password': 'تحديث كلمة المرور',
  'Create Password': 'إنشاء كلمة المرور',
  'Password updated successfully ✅': 'تم تحديث كلمة المرور بنجاح ✅',
  'Profile updated successfully ✅': 'تم تحديث الملف الشخصي بنجاح ✅',
  'Old password is required.': 'أدخل كلمة المرور الحالية.',
  'Old password is required': 'أدخل كلمة المرور الحالية.',
  'Incorrect old password': 'كلمة المرور الحالية غير صحيحة.',
  'Password must be at least 8 characters long.':
      'يجب أن تتكون كلمة المرور من ٨ أحرف على الأقل.',
  'Other country code': 'رمز دولة آخر',
  'Enter a valid mobile number.': 'أدخل رقم هاتف محمول صحيحًا.',
  'Requirements: 8+ chars': 'المتطلبات: ٨ أحرف على الأقل',
  'Password update failed. Please try again.':
      'تعذر تحديث كلمة المرور. حاول مرة أخرى.',
  'Start': 'البداية',
  'End': 'النهاية',
  'Range': 'النطاق',
  'Analyzing Farm Conditions…': 'جارٍ تحليل ظروف المزرعة…',
  'Generate AI Automation Plan': 'إنشاء خطة أتمتة ذكية',
  'Soil Moisture (%)': 'رطوبة التربة (%)',
  'Soil Temp (°C)': 'حرارة التربة (°C)',
  'Ambient Temp (°C)': 'حرارة الجو (°C)',
  'Nitrogen (mg/kg)': 'النيتروجين (ملغ/كغ)',
  'Phosphorus (mg/kg)': 'الفوسفور (ملغ/كغ)',
  'Potassium (mg/kg)': 'البوتاسيوم (ملغ/كغ)',
  'EC (µS/cm)': 'التوصيل الكهربائي (µS/cm)',
  'Apple': 'تفاح',
  'Apple scab': 'جرب التفاح',
  'Black rot': 'العفن الأسود',
  'Cedar apple rust': 'صدأ التفاح',
  'healthy': 'سليم',
  'Blueberry': 'توت أزرق',
  'Cherry (including sour)': 'كرز',
  'Powdery mildew': 'البياض الدقيقي',
  'Corn (maize)': 'ذرة',
  'Cercospora leaf spot Gray leaf spot': 'تبقع الأوراق الرمادي',
  'Common rust': 'الصدأ الشائع',
  'Northern Leaf Blight': 'لفحة الأوراق الشمالية',
  'Grape': 'عنب',
  'Esca (Black Measles)': 'مرض الإسكا',
  'Leaf blight (Isariopsis Leaf Spot)': 'لفحة أوراق العنب',
  'Orange': 'برتقال',
  'Haunglongbing (Citrus greening)': 'اخضرار الحمضيات',
  'Peach': 'خوخ',
  'Bacterial spot': 'التبقع البكتيري',
  'Pepper, bell': 'فلفل حلو',
  'Potato': 'بطاطس',
  'Early blight': 'اللفحة المبكرة',
  'Late blight': 'اللفحة المتأخرة',
  'Raspberry': 'توت العليق',
  'Soybean': 'فول الصويا',
  'Squash': 'قرع',
  'Strawberry': 'فراولة',
  'Leaf scorch': 'احتراق الأوراق',
  'Tomato': 'طماطم',
  'Leaf Mold': 'عفن الأوراق',
  'Septoria leaf spot': 'تبقع أوراق السبتوريا',
  'Spider mites Two-spotted spider mite': 'العنكبوت الأحمر ذو البقعتين',
  'Target Spot': 'التبقع المستهدف',
  'Tomato Yellow Leaf Curl Virus': 'فيروس تجعد واصفرار أوراق الطماطم',
  'Tomato mosaic virus': 'فيروس موزاييك الطماطم',
  'Now': 'الحالي',
  'No users found': 'لم يتم العثور على مستخدمين',
  'Sign in to use support.': 'سجل الدخول لاستخدام الدعم.',
  'Send a message to start a support chat.': 'أرسل رسالة لبدء محادثة مع الدعم.',
  'Delete device': 'حذف الجهاز',
  'Add device': 'إضافة جهاز',
  'Farm ID (optional)': 'رقم المزرعة (اختياري)',
  'Latitude': 'خط العرض',
  'Longitude': 'خط الطول',
  'MQTT topics (one per line)': 'موضوعات الاتصال (موضوع في كل سطر)',
  'Invalid value': 'قيمة غير صالحة',
  'Device type': 'نوع الجهاز',
  'Assigned users': 'المستخدمون المصرح لهم',
  'User details': 'تفاصيل المستخدم',
  'Save credits': 'حفظ الرصيد',
  'Feature permissions': 'صلاحيات الميزات',
  'Credit cost': 'تكلفة الاستخدام',
  'Save permissions': 'حفظ الصلاحيات',
  'credit_based': 'حسب الرصيد',
  'unlimited': 'غير محدود',
  'blocked': 'محظور',
  'devices': 'الأجهزة',
  'logs': 'سجل النشاط',
  'files': 'الملفات',
  'Sensor devices': 'أجهزة الاستشعار',
  'Actuators': 'أجهزة التحكم',
  'Pump': 'مضخة',
  'Valve': 'صمام',
  'Fan': 'مروحة',
  'On': 'يعمل',
  'Off': 'متوقف',
  'on': 'تشغيل',
  'off': 'إيقاف',
  'min': 'دقيقة',
  'No schedule': 'لا يوجد جدول',
  'Every day at': 'يومياً الساعة',
  'at': 'الساعة',
  'Sun': 'الأحد',
  'Mon': 'الاثنين',
  'Tue': 'الثلاثاء',
  'Wed': 'الأربعاء',
  'Thu': 'الخميس',
  'Fri': 'الجمعة',
  'Sat': 'السبت',
  'No controllable devices on this account yet. An administrator adds them.':
      'لا توجد أجهزة تحكم بهذا الحساب بعد. يضيفها المسؤول.',
  'Rules are checked as readings arrive, with a 10-minute cooldown.':
      'تُفحص القواعد عند وصول القراءات، بفاصل عشر دقائق بين مرات التشغيل.',
  'IoT Device Readings': 'قراءات أجهزة الاستشعار',
  'Leaf Disease Detection': 'كشف أمراض الأوراق',
  'Soil Classification': 'تصنيف التربة',
  'Yield Prediction': 'توقع الإنتاج',
  'Satellite Analysis': 'تحليل الأقمار الصناعية',
  'AI Consultant': 'المستشار الذكي',
  'PDF Report': 'تقرير بي دي إف',
  'Profile Settings': 'إعدادات الحساب',
  'Farms & Assets': 'المزارع والأصول',
  'Total AI Runs': 'إجمالي عمليات الذكاء الاصطناعي',
  'Crops in': 'محاصيل',
  'Trees in': 'أشجار',
  'Acres': 'أكر',
  'OTA command sent': 'تم إرسال أمر التحديث',
  'Connected': 'متصل',
  'Disconnected': 'غير متصل',
  'Online': 'متصل',
  'Offline': 'غير متصل',
  'Enter your readings. Values outside the allowed range are rejected.':
      'أدخل القراءات المتاحة لديك. لا تُقبل القيم خارج النطاق المسموح.',
  'Smart Farm': 'مزرعة ذكية',
  'Farm Manager': 'مدير المزرعة',
  'Report Ready': 'التقرير جاهز',
  'Generated on': 'تم الإنشاء في',
  'Report saved to': 'تم حفظ التقرير في',
  'Report downloaded successfully': 'تم تنزيل التقرير بنجاح',
  'Run this feature in the selected language first.':
      'شغّل هذه الميزة باللغة المحددة أولاً.',
  'Live weather': 'الطقس المباشر',
  'Historical readings': 'القراءات التاريخية',
  'Advanced AI': 'المساعد الذكي المتقدم',
  'Farm accounting': 'حسابات المزرعة',
  'Control & Automation': 'التحكم والأتمتة',
  'Below range': 'أقل من النطاق',
  'Above range': 'أعلى من النطاق',
  'In range': 'ضمن النطاق',
  'Temperature (°C)': 'درجة الحرارة (°C)',
  'Humidity (%)': 'الرطوبة (%)',
  'Rainfall (mm)': 'الأمطار (مم)',
  'Rice': 'أرز',
  'Maize': 'ذرة',
  'Chickpea': 'حمص',
  'Cotton': 'قطن',
  'Wheat': 'قمح',
  'Sugarcane': 'قصب السكر',
  'Tomatoes': 'طماطم',
  'Potatoes': 'بطاطس',
  'Next': 'التالي',
  'Back': 'السابق',
  'Complete setup': 'إكمال الإعداد',
  'Overview': 'نظرة عامة',
  'Users': 'المستخدمون',
  'Payments': 'المدفوعات',
  'Total Users': 'إجمالي المستخدمين',
  'Total Revenue': 'إجمالي الإيرادات',
  'Total Devices': 'إجمالي الأجهزة',
  'Pending Payments': 'المدفوعات المعلقة',
  'Thinking…': 'جارٍ التفكير…',
  'Working…': 'جارٍ العمل…',
  'Server temporarily unavailable. Please try again shortly.':
      'الخادم غير متاح مؤقتاً. حاول مرة أخرى بعد قليل.',
  'The server did not return a valid PDF. Please try again.':
      'لم يُرجع الخادم ملف تقرير صالحاً. يرجى المحاولة مرة أخرى.',
  'Network error. Please check your connection.':
      'تعذّر الاتصال. تحقق من اتصالك بالإنترنت.',
  'Invalid username or password': 'اسم المستخدم أو كلمة المرور غير صحيحة',
  'Invalid credentials': 'بيانات الدخول غير صحيحة',
  'Name is required.': 'الاسم مطلوب.',
  'Required': 'مطلوب',
  'Unspecified': 'غير محدد',
  'Soil': 'التربة',
  'Crop': 'المحصول',
  'Irrigation': 'الري',
  'History': 'السجل',
  'Updated': 'آخر تحديث',
  'Last seen': 'آخر اتصال',
  'Current': 'الحالي',
  'Past': 'السابق',
  'Radius': 'نصف القطر',
  'Max cloud cover': 'الحد الأقصى للغطاء السحابي',
  'AI Confidence': 'ثقة النموذج',
  'Farm': 'المزرعة',
  'Shared Credits': 'الرصيد المشترك',
  'Health': 'الحالة الصحية',
  'Role': 'الدور',
  'Plan': 'الخطة',
  'Method': 'الطريقة',
  'Date': 'التاريخ',
  'Free': 'مجانية',
  'Admin': 'مسؤول',
  'User': 'مستخدم',
  'Bank': 'البنك',
  'Account Name': 'اسم الحساب',
  'Phone number': 'رقم الهاتف',
  'Copied to clipboard': 'تم النسخ',
  'Transfer to': 'حوّل إلى',
  'National Bank of Egypt (NBE)': 'البنك الأهلي المصري',
  'Confirm the diagnosis with an agricultural specialist before choosing treatment.':
      'استشر مختصاً زراعياً لتأكيد التشخيص قبل اختيار العلاج.',
  'No readings in this range': 'لا توجد قراءات في هذه الفترة',
  'Not reported for this period': 'لا توجد بيانات لهذه الفترة',
  'Camera': 'الكاميرا',
  'Gallery': 'المعرض',
  'Pick location': 'اختيار الموقع',
  'Toggle satellite': 'تبديل عرض القمر الصناعي',
  'Coming soon': 'قريباً',
  'or': 'أو',
  'Entity type': 'نوع الحساب',
  'Individual': 'فرد',
  'Company': 'شركة',
  'Company name': 'اسم الشركة',
  'Age': 'العمر',
  'Gender': 'الجنس',
  'Male': 'ذكر',
  'Female': 'أنثى',
  'Other': 'أخرى',
  'Farms & locations (optional)': 'المزارع والمواقع (اختياري)',
  'Add another farm': 'إضافة مزرعة أخرى',
  'Farm name': 'اسم المزرعة',
  'Farm Name': 'اسم المزرعة',
  'Area (Ha)': 'المساحة (هكتار)',
  'Crops': 'المحاصيل',
  'Add crop': 'إضافة محصول',
  'Crop name': 'اسم المحصول',
  'Area': 'المساحة',
  'Tree / palm crop?': 'محصول أشجار أو نخيل؟',
  'Tree name': 'اسم الشجرة',
  'Code': 'الرمز',
  'Add tree': 'إضافة شجرة',
  'Conversation History': 'سجل المحادثات',
  'New Chat': 'محادثة جديدة',
  'No previous conversations yet.': 'لا توجد محادثات سابقة بعد.',
  'Attach image': 'إرفاق صورة',
  'Stop response': 'إيقاف الرد',
  'Payment Method': 'طريقة الدفع',
  'Vodafone Cash': 'فودافون كاش',
  'InstaPay': 'إنستاباي',
  'Bank Transfer': 'تحويل بنكي',
  'Beneficiary Instructions': 'تعليمات التحويل للمستفيد',
  'Enter an amount and attach a receipt image.':
      'أدخل المبلغ وأرفق صورة الإيصال.',
  'Receipt submitted. Credits arrive after approval.':
      'تم إرسال الإيصال. يُضاف الرصيد بعد الموافقة.',
  'Include your account email or reference in the transfer notes.':
      'أدرج بريد حسابك أو مرجع التحويل في ملاحظات التحويل.',
  'You receive 10 credits per EGP unit once approved by an admin.':
      'تحصل على ١٠ نقاط لكل جنيه مصري بعد موافقة المسؤول.',
  'Amount paid': 'المبلغ المدفوع',
  'e.g. 100': 'مثال: ١٠٠',
  'Transfer Reference / Transaction ID (optional)':
      'مرجع التحويل أو رقم العملية (اختياري)',
  'e.g. TXN12345678': 'مثال: TXN12345678',
  'Attach receipt screenshot': 'إرفاق صورة الإيصال',
  'Analysis context': 'سياق التحليل',
  'Include my profile': 'تضمين بيانات حسابي',
  'Include macro weather': 'تضمين بيانات الطقس',
  'Ask about your farm…': 'اسأل عن مزرعتك…',
  'Live relay and device telemetry with real-time feedback.':
      'قراءات الأجهزة والتحكم مع متابعة الحالة مباشرة.',
  'Are you sure you want to remove this automation schedule?':
      'هل تريد حذف جدول الأتمتة هذا؟',
  'Autonomous Agronomy Engine': 'مساعد الأتمتة الزراعية',
  'Generates science-backed pump & lighting schedules using live IoT telemetry.':
      'يُنشئ جداول للمضخات والإضاءة استناداً إلى قراءات أجهزة المزرعة.',
  'Brightness': 'السطوع',
  'Colour': 'اللون',
  'Apply': 'تطبيق',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Rule name': 'اسم القاعدة',
  'Morning irrigation': 'الري الصباحي',
  'Device': 'الجهاز',
  'Turn on': 'تشغيل',
  'Turn off': 'إيقاف',
  'Run for (minutes, optional)': 'مدة التشغيل (دقائق، اختياري)',
  'No sensor devices available to read from.':
      'لا توجد أجهزة استشعار متاحة للقراءة.',
  'Read sensor from': 'قراءة المستشعر من',
  'Sensor': 'المستشعر',
  'Is': 'الشرط',
  'below': 'أقل من',
  'at or below': 'أقل من أو يساوي',
  'above': 'أكبر من',
  'at or above': 'أكبر من أو يساوي',
  'exactly': 'يساوي',
  'Value': 'القيمة',
  'Edit Global Farm Context': 'تعديل سياق المزرعة العام',
  'Edit Farm Context': 'تعديل سياق المزرعة',
  'Soil Type': 'نوع التربة',
  'Crop Type': 'نوع المحصول',
  'Location / Region': 'الموقع أو المنطقة',
  'Irrigation Type': 'نوع الري',
  'Save Context': 'حفظ السياق',
  'IoT telemetry auto-filled successfully!':
      'تم ملء قراءات أجهزة الاستشعار بنجاح.',
  'IoT sensor telemetry synced successfully!':
      'تمت مزامنة قراءات أجهزة الاستشعار بنجاح.',
  'No live IoT sensor data found for bound devices.':
      'لا توجد قراءات مباشرة للأجهزة المرتبطة.',
  'Please correct invalid field values.': 'يرجى تصحيح قيم الحقول غير الصالحة.',
  'Please correct invalid input values.':
      'يرجى تصحيح القيم المدخلة غير الصالحة.',
  'Crop Recommendation': 'توصيات المحاصيل',
  'Discover optimal crop pairings based on soil analytics and environmental factors.':
      'تعرّف على المحاصيل المناسبة بناءً على تحليل التربة والعوامل البيئية.',
  'Global Farm Context': 'سياق المزرعة العام',
  'Edit Context': 'تعديل السياق',
  'Step 1 · Soil Origin': 'الخطوة ١ · التربة',
  'Clear': 'مسح',
  'Upload Soil Image': 'رفع صورة التربة',
  'Tap to capture or select a soil photo (5 ⚡)':
      'اضغط لالتقاط صورة التربة أو اختيارها (٥ ⚡)',
  'SCANNING SOIL MATRIX...': 'جارٍ تحليل التربة…',
  'Identify Soil': 'تحديد نوع التربة',
  'DETECTED SOIL': 'التربة المكتشفة',
  'Soil Identification Analysis': 'تحليل نوع التربة',
  'Step 2 · Local Environment': 'الخطوة ٢ · البيئة المحلية',
  'Auto-fill IoT': 'ملء من أجهزة الاستشعار',
  'Submit parameters to generate optimal crop yields.':
      'أرسل القيم للحصول على توصيات المحاصيل المناسبة.',
  'New Analysis': 'تحليل جديد',
  'No live data from this device yet. Try Refresh, or use Manual entry.':
      'لا توجد قراءات مباشرة لهذا الجهاز بعد. حدّث البيانات أو أدخلها يدوياً.',
  'Device location': 'موقع الجهاز',
  'Fix the highlighted values first.': 'صحّح القيم المحددة أولاً.',
  'Unbind device?': 'إلغاء ربط الجهاز؟',
  'Controls': 'عناصر التحكم',
  'Add': 'إضافة',
  'No controls yet. Add a switch or value endpoint.':
      'لا توجد عناصر تحكم بعد. أضف مفتاحاً أو عنصر تحكم بقيمة.',
  'Label': 'الاسم المعروض',
  'Command topic': 'موضوع الأوامر',
  'State topic (optional)': 'موضوع الحالة (اختياري)',
  'Switch': 'مفتاح',
  'On payload': 'رسالة التشغيل',
  'Off payload': 'رسالة الإيقاف',
  'Min': 'الحد الأدنى',
  'Max': 'الحد الأقصى',
  'Unit': 'الوحدة',
  'Pick a firmware file first.': 'اختر ملف البرنامج الثابت أولاً.',
  'Set an OTA topic first (edit the device).':
      'حدد موضوع التحديث عن بُعد أولاً من تعديل الجهاز.',
  'Firmware': 'البرنامج الثابت',
  'Version': 'الإصدار',
  'Push update (OTA)': 'إرسال التحديث عن بُعد',
  'Edit device': 'تعديل الجهاز',
  'Name': 'الاسم',
  'Location': 'الموقع',
  'MQTT topics': 'موضوعات الاتصال',
  'Topic': 'الموضوع',
  'Add topic': 'إضافة موضوع',
  'OTA topic': 'موضوع التحديث عن بُعد',
  'Bind device': 'ربط جهاز',
  'Enter a device name.': 'أدخل اسم الجهاز.',
  'Bind a device': 'ربط جهاز',
  'Device name': 'اسم الجهاز',
  'MQTT topics (monitored)': 'موضوعات الاتصال المراقَبة',
  'e.g. farm/soil/device1': 'مثال: farm/soil/device1',
  'OTA topic (optional)': 'موضوع التحديث عن بُعد (اختياري)',
  'topic the device listens on for firmware':
      'الموضوع الذي يستقبل الجهاز عبره تحديثات البرنامج الثابت',
  'Farm Context': 'سياق المزرعة',
  'Select Farm': 'اختر المزرعة',
  '-- Select Farm --': '— اختر المزرعة —',
  'Select Crop': 'اختر المحصول',
  '-- Select Crop --': '— اختر المحصول —',
  'Select Tree': 'اختر الشجرة',
  '-- Select Tree --': '— اختر الشجرة —',
  'Tap to add a leaf photo': 'اضغط لإضافة صورة ورقة النبات',
  'YOLO Segmentation & Glow Mask': 'تحديد الورقة وقناعها المضيء',
  'Add farm': 'إضافة مزرعة',
  'New farm': 'مزرعة جديدة',
  'Address': 'العنوان',
  'Total area (Ha)': 'المساحة الكلية (هكتار)',
  'No crops recorded.': 'لا توجد محاصيل مسجلة.',
  'No trees recorded.': 'لا توجد أشجار مسجلة.',
  'Name is required': 'الاسم مطلوب',
  'Please enter a valid member email': 'أدخل بريداً إلكترونياً صالحاً للعضو',
  'Personal Information': 'المعلومات الشخصية',
  'Mobile Number': 'رقم الهاتف المحمول',
  'Date of Birth': 'تاريخ الميلاد',
  'Save Changes': 'حفظ التغييرات',
  'Old Password': 'كلمة المرور الحالية',
  'New Password': 'كلمة المرور الجديدة',
  'Team Management': 'إدارة الفريق',
  'No team members added yet.': 'لم تتم إضافة أعضاء للفريق بعد.',
  'Add New Member': 'إضافة عضو جديد',
  'Member Email': 'البريد الإلكتروني للعضو',
  'Shared Credits (optional)': 'الرصيد المشترك (اختياري)',
  'Leave blank to share full balance': 'اتركه فارغاً لمشاركة الرصيد بالكامل',
  'Add Member': 'إضافة عضو',
  'My Farms': 'مزارعي',
  'No farms added yet.': 'لم تتم إضافة مزارع بعد.',
  'Add New Farm': 'إضافة مزرعة جديدة',
  'Total Area (Acres)': 'المساحة الكلية (أكر)',
  'Add Farm': 'إضافة مزرعة',
  'No crops registered for this farm.': 'لا توجد محاصيل مسجلة لهذه المزرعة.',
  'Add New Crop': 'إضافة محصول جديد',
  'Crop Name (e.g. Wheat)': 'اسم المحصول (مثال: قمح)',
  'Planted Area': 'المساحة المزروعة',
  'Category': 'الفئة',
  'Cereal': 'حبوب',
  'Fruit': 'فاكهة',
  'Vegetable': 'خضروات',
  'Add Crop': 'إضافة محصول',
  'No trees registered for this crop.': 'لا توجد أشجار مسجلة لهذا المحصول.',
  'Add New Tree': 'إضافة شجرة جديدة',
  'Tree Name': 'اسم الشجرة',
  'Tree Code (e.g. TR-01)': 'رمز الشجرة (مثال: TR-01)',
  'Add Tree': 'إضافة شجرة',
  'Report generated successfully!': 'تم إنشاء التقرير بنجاح.',
  'Please generate the report first.': 'يرجى إنشاء التقرير أولاً.',
  'Generate & Share PDF Report': 'إنشاء تقرير ومشاركته',
  'Farmer / Reporter Name': 'اسم المزارع أو مُعدّ التقرير',
  'Report Sections': 'أقسام التقرير',
  'Generate Report  ·  5 ⚡': 'إنشاء التقرير · ٥ ⚡',
  'Share': 'مشاركة',
  'Download': 'تنزيل',
  'Location permission was denied.': 'لم يتم منح إذن الوصول إلى الموقع.',
  'Tap the map to set a point or draw a polygon.':
      'اضغط على الخريطة لتحديد نقطة أو رسم مضلع.',
  'Polygon mode': 'وضع المضلع',
  'Compare with past': 'المقارنة مع الماضي',
  'weeks': 'أسابيع',
  'months': 'أشهر',
  'years': 'سنوات',
  'Analyze  ·  5 ⚡': 'تحليل · ٥ ⚡',
  'Upload an aerial image to count palm trees (5 ⚡).':
      'ارفع صورة جوية لعدّ أشجار النخيل (٥ ⚡).',
  'palm trees detected': 'شجرة نخيل مكتشفة',
  'Type a message…': 'اكتب رسالة…',
  'Yield Prediction Model': 'توقع إنتاج المحصول',
  'Estimate total crop harvest volume utilizing environmental ML analytics.':
      'قدّر كمية المحصول باستخدام تحليل الظروف البيئية.',
  'Crop Selection': 'اختيار المحصول',
  'Soil & Environmental Telemetry': 'قراءات التربة والبيئة',
  'Auto-fill IoT Data': 'ملء من أجهزة الاستشعار',
  'Platform Telemetry & Analytics': 'إحصاءات المنصة وتحليلاتها',
  'High-level metrics across all GeoNutria user activity.':
      'مؤشرات عامة لنشاط مستخدمي المنصة.',
  'Search users by name or email…': 'ابحث بالاسم أو البريد الإلكتروني…',
  'Reject': 'رفض',
  'Approve & Credit': 'موافقة وإضافة الرصيد',
  'AI Health Diagnosis': 'تشخيص صحة النبات',
  'Healthy': 'سليم',
  'Moderate': 'إجهاد متوسط',
  'Moderate Stress': 'إجهاد متوسط',
  'High': 'مرتفع',
  'High Stress': 'إجهاد شديد',
  'No Live Data': 'لا توجد قراءات مباشرة',
  'Unknown': 'غير معروف',
  'Soil Moisture': 'رطوبة التربة',
  'Moisture': 'الرطوبة',
  'Soil Temp': 'حرارة التربة',
  'Ambient Temp': 'حرارة الجو',
  'Temp': 'الحرارة',
  'Humidity': 'الرطوبة الجوية',
  'Soil pH': 'حموضة التربة',
  'Nitrogen (N)': 'النيتروجين (N)',
  'Phosphorus (P)': 'الفوسفور (P)',
  'Potassium (K)': 'البوتاسيوم (K)',
  'Salinity': 'الملوحة',
  'Light': 'الإضاءة',
  'Low': 'منخفض',
  'Good': 'جيد',
  'Optimal': 'مثالي',
  'Rain': 'الأمطار',
  'Cloud': 'السحب',
  'Wind': 'الرياح',
  'Solar': 'الإشعاع الشمسي',
  'Air temperature': 'درجة حرارة الهواء',
  'Relative humidity, 0–100%': 'الرطوبة النسبية، ٠–١٠٠٪',
  'Total rainfall in each interval. 0 mm means no rain was recorded.':
      'مجموع الأمطار في كل فترة. الصفر يعني عدم تسجيل أمطار.',
  'Share of sky covered, 0–100%. 0% means clear sky.':
      'نسبة تغطية السماء بالسحب، ٠–١٠٠٪. الصفر يعني سماء صافية.',
  'Wind speed': 'سرعة الرياح',
  'Solar radiation': 'الإشعاع الشمسي',
  'IoT sensors': 'مستشعرات المزرعة',
  'Leaf diagnosis': 'تشخيص الأوراق',
  'Soil analysis': 'تحليل التربة',
  'Crop recommendation': 'توصيات المحاصيل',
  'Yield prediction': 'توقع الإنتاج',
  'AI consultant': 'المستشار الذكي',
  'Satellite': 'الأقمار الصناعية',
  "Support is offline. Reopen this page to reconnect.":
      "الدعم غير متصل. أعد فتح الصفحة للاتصال من جديد.",
  "Report IoT Sensor issue": "الإبلاغ عن مشكلة في مستشعرات المزرعة",
  "Subscription & Top-up help": "المساعدة في الاشتراك وشحن الرصيد",
  "Irrigation Automation inquiry": "استفسار عن أتمتة الري",
  "Thanks for reaching out! A human agent will be with you shortly.":
      "شكراً لتواصلك معنا! سيتواصل معك أحد ممثلي الدعم قريباً.",
  "Account Number": "رقم الحساب",
  "GeoNutria Farm Report": "تقرير مزرعة جيو نيوتريا",
  "Save Report PDF": "حفظ التقرير بصيغة PDF",
  "Remove this device from your account?": "هل تريد إزالة هذا الجهاز من حسابك؟",
  "Reconnect support · 1 credit": "إعادة الاتصال بالدعم · نقطة واحدة",
  "Test MQTT connection": "اختبار اتصال المستشعرات",
  "Actuator": "جهاز التحكم",
  "Device satellite imagery": "صور الأقمار الصناعية لمواقع الأجهزة",
};
